kind = "mobile"
previewPath = "/"
title = "السوري معك"
version = "1.0.0"
id = "artifacts/alsouri-maak"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19190

[services.development]
run = "pnpm --filter @workspace/alsouri-maak run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/alsouri-maak", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/alsouri-maak", "run", "serve" ]

[services.env]
PORT = "19190"
BASE_PATH = "/"
